### ISSUE TITLE
No README.md and no hint athat this replaces gitdb

### ISSUE THREAD

**Issue by nkadel** [gitpython-developers/gitdb#57]
Updating the gitdb module is understandable, but changing the package name to "gitdb2" while actually installing modules named "gitdb" is confusing. Doing so without any hint that this module overhaps deployments of gitdb is dangerous: this showed up when I was trying to RPM building this software for AWX deployment and saw the conflicts.

**Comment by Harmon758** [comment]
[A request to recover the PyPI account that owns `gitdb` has been made recently](https://github.com/pypa/pypi-support/issues/204).
If the account is successfully recovered, I'd like to transition back to using the original `gitdb` package name and have `gitdb2` simply be a mirror package.
Otherwise, if the request fails, I'll update the documentation accordingly.

**Comment by nkadel** [comment]
Good thanks! It confused me quite a lot when I was trying to RPM package it for the awx dependency.

**Comment by Harmon758** [comment]
This should now be resolved with the changes detailed in #59.
`gitdb` is now the name of the package again, with `gitdb2` just being a mirror package that requires `gitdb`.

**Comment by nkadel** [comment]
Great, I'm glad you could resolve that.
