### ISSUE TITLE
smmap 5.0.0 support

### ISSUE THREAD

**Issue by DmitryKuzmenko** [gitpython-developers/gitdb#76]
Is it possible to bump the `smmap` version to `5.0.0`?
It is the current version in ArchLinux repository and this is breaking packages depending on `gitdb` like `git-up`.
I tried to bump the `smmap` version. Tests passed with `smmap-5.0.0` on ArchLinux.

**Comment by Byron** [comment]
I am happy to do that! This also means the bug was introduced in the arch package manager which seems to pair incompatible crates while not trying to rebuild all dependencies with the new version, potentially causing widespread breakage, not only with GitPython.

[v4.0.8](https://pypi.org/project/gitdb/4.0.8/) was released, avoiding to major bump this one to avoid similar issues to arise on arch. By now I feel there is no way to do it right.

I am closing this issue as new version constraints were set to include smmap 5.0, and also drop support for py3.4 and 3.5  to match smmap.
